# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: rsyncer
version: '0.0.1'
github: "huseyinyilmaz/rsyncer"
license: MIT
author: "Huseyin Yilmaz"
maintainer: "Huseyin Yilmaz"
synopsis: Calls rsync on file changes
description: rsyncer is a tool to use sync projects accross machines.
category: utility

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.rst
- stack.yaml

ghc-options: -Wall

default-extensions:
  - OverloadedStrings
  - DeriveGeneric

library:
  dependencies:
  - base
  - text
  - fsnotify
  - turtle
  - aeson
  - yaml
  - bytestring
  - directory
  - exceptions
  source-dirs: library

executables:
  rsyncer:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - rsyncer
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  rsyncer-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - rsyncer
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  rsyncer-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - rsyncer
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
